### ISSUE TITLE
Easier usage and self-containment of package

### ISSUE THREAD

**Issue by AlickH** [Tristan971/Lyrical#2]
How can I use it. Thanks = =

**Comment by Tristan971** [comment]
It is used by downloading the latest release jar file (https://github.com/Tristan971/Lyrical/releases) then double clicking it or running `java -jar filename.jar`.

At the moment, MusixMatch changed their API a few days ago so it is broken but I will fix it very soon and provide self-contained packages as well. Stay tuned.

**Comment by SIDmao** [comment]
Got it. Thanks very much!
